### PR TITLE
refactor: prefer inheritance over builder for alg

### PR DESCRIPTION
**Pull request by brownoxford**
## What kind of change does this PR introduce?

This PR refactors the `JWTAlgorithmBuilder` functionality into classes which inherit from `JWTAlgorithm`. Several deprecation warnings have been added, but this shouldn't break BC. If you are ok with a BC break, the entire `JWTAlgorithmBuilder` class can be removed (with appropriate `README.md` updates for removal of `random_secret`)

The new code is easier to understand and maintain, and no longer requires things like JWTAlgorithmBuilder needing to access private properties of JWTAlgorithm, or for JWTAlgorithm to maintain private members that it only needs for certain algorithm types.

### CODE REVIEW

**Comment by fenix-hub** [comment]
I'm ok with refactoring the whole class.
The builder pattern I implemented came from my OOP base (Java) so it was just a pretty much "automatic" implementation.
Taking the fact that GDScript is more of a toy scripting language and objects are not really a thing, I'm ok with a more versatile and less verbose approach.
Mind completing the PR with the now implementation?

**Comment by brownoxford** [comment]
Absolutely, by "new implementation", do you mean remove the JWTAlgorithmBuilder class entirely?

**Comment by fenix-hub** [comment]
> Absolutely, by "new implementation", do you mean remove the JWTAlgorithmBuilder class entirely?

Yes, exactly that

**Comment by brownoxford** [comment]
Ok, `JWTAlgorithmBuilder` has been removed!

**Comment by fenix-hub** [comment]
Thank you very much! :)

**Pull request merged**
