### PR TITLE
Switched to Godot 4 support, Repaired broken RS256 implementation.

### PR DESCRIPTION
**Pull request by crazychenz**
- Replaced Godot 3.x support for Godot 4 support. Suggest pulling into a godot4 branch.
- Repaired RS256 support. It was originally using encrypt() instead of sign(). Verified output with https://jwt.io/
- Added alias RS256 for RSA256 and HS256 for HSA256 so that the documentation is correct without breaking existing API assumptions.
- Renamed header algorithms to match JWT standard.
- Other small fixes (e.g. respecting passed parameters, minor style changes, renamed Exceptions enum to JWTExceptions)
- Created a demo @ [https://github.com/crazychenz/godot-engine.jwt-demo](https://github.com/crazychenz/godot-engine.jwt-demo)

### CODE REVIEW

**Comment by fenix-hub** [comment]
Hi and thank you very much for your work.
Does this have backward compatibility with previous Godot versions?

**Comment by fenix-hub** [comment]
@crazychenz
I guess not, still I'll cherry pick some fixes of your pr into the current main (or I'll let you do so if you want)

**Comment by crazychenz** [comment]
@fenix-hub, np. yeah, I'm sure you've figured out, Godot 4 has some new major GDScript changes. I'll likely do some Godot 3 cherry picks when/if I use OpenAuth for any of my Godot 3 projects (I've got one that may be likely). This specific port is for some longer term projects that aren't likely to be near complete until well after Godot 4 is stable.

**Comment by fenix-hub** [comment]
@crazychenz No problem, thank you again for contributing! 🙌

**Pull request merged**
